language: php

php:
    - 5.6
    - 7.0

env:
  - NEO_VERSION="2.1.6"
  - NEO_VERSION="2.1.7"
  - NEO_VERSION="2.1.8"
  - NEO_VERSION="2.2.0"
  - NEO_VERSION="2.2.1"
  - NEO_VERSION="2.2.2"
  - NEO_VERSION="2.2.3"

before_install:
    - sudo apt-get update > /dev/null
    - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz > null
    - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz > null
    - neo4j-community-$NEO_VERSION/bin/neo4j start > null

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction

matrix:
  allow_failures:
    - php: 7.0

script:
    - ./tests/neo_setup.sh
    - vendor/bin/phpunit

notifications:
    email: "willemsen.christophe@gmail.com"